"""LLM-generated greetings: replace static greeting texts with instructions

The clinic-editable `greeting_message` / `voice_greeting_message` columns held a
static opening line, but the greeting is now generated by the agent itself on
every session start. This replaces them with `greeting_instructions`: free-text
guidance from the clinic admin that is injected into the system prompt so the
LLM greets in the clinic's preferred style. Existing greeting text is carried
over as the initial instruction (it reads naturally as an example to follow).

Revision ID: 0022
Revises: 0021
"""

from alembic import op

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE clinics ADD COLUMN IF NOT EXISTS greeting_instructions TEXT")
    op.execute(
        "UPDATE clinics SET greeting_instructions = greeting_message "
        "WHERE greeting_instructions IS NULL AND greeting_message IS NOT NULL "
        "AND greeting_message <> ''"
    )
    op.execute("ALTER TABLE clinics DROP COLUMN IF EXISTS greeting_message")
    op.execute("ALTER TABLE clinics DROP COLUMN IF EXISTS voice_greeting_message")


def downgrade() -> None:
    op.execute("ALTER TABLE clinics ADD COLUMN IF NOT EXISTS greeting_message TEXT")
    op.execute("ALTER TABLE clinics ADD COLUMN IF NOT EXISTS voice_greeting_message TEXT")
    op.execute(
        "UPDATE clinics SET greeting_message = greeting_instructions "
        "WHERE greeting_message IS NULL AND greeting_instructions IS NOT NULL"
    )
    op.execute("ALTER TABLE clinics DROP COLUMN IF EXISTS greeting_instructions")
